### ISSUE TITLE
Error 500 when trying to open configuration link under plugin.

### ISSUE THREAD

**Issue by Eldadc** [jamtur01/redmine_tab#12]
Hi,

I'm getting 500 error when trying to open configuration link. I have installed the latest Redmine Bitmani  version.
Any suggestions will very helpful.

Thanks

**Comment by fathomssen** [comment]
I have created a pull request which would solve this problem: https://github.com/jamtur01/redmine_tab/pull/18

For the time being, you can also use my fork: https://github.com/fathomssen/redmine_tab

**Comment by Eldadc** [comment]
Thanks for resolving the issues.
