### ISSUE TITLE
Settings page not found

### ISSUE THREAD

**Issue by enricodeleo** [jamtur01/redmine_tab#17]
Hello!
I tried with Redmine 3.x and, after turning the `match` into `get` within `routes.rb`, everything seems to work everywhere but in the setting page where I get a Page not found error.

Any Ideas?

**Comment by fathomssen** [comment]
I have created a pull request which would solve this problem: https://github.com/jamtur01/redmine_tab/pull/18

For the time being, you can also use my fork: https://github.com/fathomssen/redmine_tab

**Comment by enricodeleo** [comment]
@fathomssen Thank you! I'm going to try it now :)
