### ISSUE TITLE
Multiple Tabs

### ISSUE THREAD

**Issue by jrc03c** [jamtur01/redmine_tab#5]
This plugin is awesome!  The only thing lacking (in my opinion) is the ability to create multiple tabs!

**Comment by astebert** [comment]
Hi,
Do you plan to add the multiple tab functionality in the future ?

**Comment by jamtur01** [comment]
No plans. I haven't used Redmine in 5 years and have no plans to update this plugin. Perhaps one of the forks may be more up-to-date.

**Comment by astebert** [comment]
thanks for your instant reply.
I'll search in the differents forks.

Thanks,
Bert


Le 12/06/2015 02:20, James Turnbull a écrit :
>
> No plans. I haven't used Redmine in 5 years and have no plans to 
> update this plugin. Perhaps one of the forks may be more up-to-date.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/jamtur01/redmine_tab/issues/5#issuecomment-111312987>.
>

-- 

*Bertrand FRUCHET*
bertrand@greenitsolutions.fr <mailto:bertrand@greenitsolutions.fr>
GSM : 06.28.79.91.09

	

43, rue du 24 Février
79000 NIORT
Tel : 05.49.24.18.10
Web : http://www.greenitsolutions.fr
SIREN 532 920 790 - APE 6203Z - TVA FR40532920790
